# Copyright 2024 Bytedance Ltd. and/or its affiliates
# Updated by AgentTestable
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Optional

from torch.utils.data import SequentialSampler
from torchdata.stateful_dataloader import StatefulDataLoader
from transformers import PreTrainedTokenizer, ProcessorMixin

from curriculum.utils.rl_dataset import AutoGeneratedRLHFDataset, collate_fn

def create_dataloader(config, tokenizer: PreTrainedTokenizer, processor: Optional[ProcessorMixin]) -> StatefulDataLoader:
    print(f"Ignore Train files: {config.train_files}")
    print(f"Ignore Val files: {config.val_files}")
    train_dataset = AutoGeneratedRLHFDataset(
        tokenizer=tokenizer,
        processor=processor,
        prompt_key=config.prompt_key,
        image_key=config.image_key,
        max_prompt_length=config.max_prompt_length,
        truncation=config.truncation,
        custom_format_prompt=config.custom_format_prompt,
        custom_fake_data_size=config.custom_fake_data_size,
    )
    sampler = SequentialSampler(data_source=train_dataset)

    # Group data into train_batch size
    # Example: 
    # - there are 100 items in the train_dataset
    # - the config.train_batch_size is 10
    # - then the train_dataloader is 100 / 10 = 10
    train_dataloader = StatefulDataLoader(
        dataset=train_dataset,
        batch_size=config.train_batch_size,
        sampler=sampler,
        num_workers=8,
        collate_fn=collate_fn,
        pin_memory=False,
        drop_last=True,
    )

    assert len(train_dataloader) >= 1
    print(f"Size of train dataloader(batches): {len(train_dataloader)}")
    return train_dataloader
